name: ipyvolume
channels:
 - conda-forge
dependencies:
 - ipyvolume
 - pyvista
 - geopandas
 - ipywidgets>=6.0.0
 - pathlib2
 - pip
 - pip:
    - git+https://github.com/GNS-Science/eq-fault-geom.git@willic3_add_shp_to_vtk
# - nest-asyncio
