name: ipyvolume
channels:
 - conda-forge
dependencies:
 - ipyvolume
 - pyvista
 - geopandas
 - nest-asyncio
 - ipywidgets>=6.0.0
 - pip
 - pip:
    - git+https://github.com/GNS-Science/eq-fault-geom.git@willic3-add-shp-to-vtk
